#!/usr/bin/env python3
"""업로드 매니페스트(manifest.json)를 PR 댓글용 번호 목록 마크다운으로 바꾼다 (임시 도구 — merge 전 제거)."""
import json
import sys


def render(manifest):
    entries = manifest["images"]
    uploaded = [e for e in entries if "duplicateOf" not in e]
    lines = [f"## 시연용 사진 S3 업로드 결과 ({len(uploaded)}장 업로드, 중복 {len(entries) - len(uploaded)}장 재사용)", ""]
    for number, entry in enumerate(entries, start=1):
        urls = entry.get("urls") or {}
        if "duplicateOf" in entry:
            lines.append(f"{number}. `{entry['name']}` — 중복: `{entry['duplicateOf']}` 와 같은 사진이라 같은 링크를 사용합니다")
            continue
        check = entry.get("publicCheck", {})
        ok = "OK" if check and all(c["ok"] for c in check.values()) else "확인 필요"
        lines.append(f"{number}. `{entry['name']}` — imageId `{entry.get('imageId')}` ({ok})")
        for variant in ("1280w", "640w", "320w"):
            if variant in urls:
                lines.append(f"   - {variant}: {urls[variant]}")
    attach = manifest.get("attach")
    if attach:
        lines += ["", ("✅ " if attach["ok"] else "⚠️ ") + f"상품 {attach['productId']} 연결: {attach['message']}"
                  + ("" if attach["ok"] else " — 연결되지 않은 업로드는 24시간 뒤 자동 삭제됩니다.")]
    lines += ["", "AI 생성 요청의 `images`에는 위 `imageId`(또는 1280w 링크)를 번호 순서대로 넣으면 됩니다. 첫 번째가 대표 사진입니다.",
              "", "---", "_Generated by [Claude Code](https://claude.ai/code)_"]
    return "\n".join(lines)


if __name__ == "__main__":
    path = sys.argv[1] if len(sys.argv) > 1 else "manifest.json"
    with open(path, encoding="utf-8") as handle:
        print(render(json.load(handle)))
