-- 시연용 실사풍 이미지(AI 생성)로 상품 대표·상세 이미지를 바꾼다. 원본: scripts/demo-products/photoreal_migration.py
-- 이미지는 docs/demo-products/photoreal/staging/*.webp. A=대표, B=상세 1번, C=상세 2번.
-- 큐레이션 33개는 상품명+장인 ID, 대표 56·상품별 이미지 158개는 상품명+소분류 ID 로 찾는다.
-- A·B·C 가 모두 있으면 2번 이후 상세를 지우고, A 만 있으면 상세를 지운다(일러스트가 섞이지 않게). 시드 상품(저장소 docs 이미지)만 바꾼다.

CREATE TEMP TABLE demo_photoreal_c (title VARCHAR(200), artisan_id BIGINT, main_url VARCHAR(500),
    detail0_url VARCHAR(500), detail1_url VARCHAR(500)) ON COMMIT DROP;
INSERT INTO demo_photoreal_c VALUES
    ('연분홍 모시 생활한복 저고리', 31, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p01_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p01_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p01_C.webp'),
    ('쪽빛 누비 복주머니', 31, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p02_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p02_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p02_C.webp'),
    ('매화 자수 손수건 세트', 31, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p03_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p03_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p03_C.webp'),
    ('오방색 조각보 파우치', 31, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p04_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p04_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p04_C.webp'),
    ('연둣빛 모시 스카프', 31, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p05_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p05_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p05_C.webp'),
    ('홍매 삼작 노리개', 36, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p06_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p06_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p06_C.webp'),
    ('쪽빛 매듭 키링', 36, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p07_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p07_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p07_C.webp'),
    ('조각보 카드지갑', 36, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p08_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p08_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p08_C.webp'),
    ('은빛 매화 비녀', 36, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p09_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p09_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p09_C.webp'),
    ('옥빛 매듭 귀걸이', 36, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p10_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p10_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p10_C.webp'),
    ('수자수 모란도 액자', 25, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p11_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p11_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p11_C.webp'),
    ('한지 산수화 액자', 25, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p12_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p12_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p12_C.webp'),
    ('오방 누비 방석', 25, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p13_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p13_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p13_C.webp'),
    ('모시 테이블 러너', 25, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p14_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p14_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p14_C.webp'),
    ('한지 무드 조명', 25, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p15_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p15_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p15_C.webp'),
    ('하늘빛 한산모시 스카프', 32, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p16_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p16_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p16_C.webp'),
    ('모시 주방 앞치마', 32, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p17_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p17_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p17_C.webp'),
    ('모시 홑이불', 32, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p18_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p18_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p18_C.webp'),
    ('민트 모시 보자기', 32, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p19_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p19_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p19_C.webp'),
    ('모시 개량한복 상의', 32, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p20_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p20_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p20_C.webp'),
    ('은 매듭 팔찌', 34, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p21_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p21_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p21_C.webp'),
    ('옥 노리개 브로치', 34, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p22_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p22_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p22_C.webp'),
    ('칠보 푸른 반지', 34, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p23_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p23_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p23_C.webp'),
    ('금빛 떨잠', 34, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p24_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p24_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p24_C.webp'),
    ('진주 매듭 목걸이', 34, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p25_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p25_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p25_C.webp'),
    ('나전 명함집', 40, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p26_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p26_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p26_C.webp'),
    ('나전 필통', 40, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p27_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p27_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p27_C.webp'),
    ('칠보 문양 만년필', 40, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p28_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p28_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p28_C.webp'),
    ('서예 붓·먹·벼루 세트', 40, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p29_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p29_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p29_C.webp'),
    ('한지 편지지 세트', 40, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p30_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p30_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p30_C.webp'),
    ('전주 합죽선 · 매화선', 41, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p31_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p31_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p31_C.webp'),
    ('청자 운학문 찻잔', 20, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p32_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p32_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p32_C.webp'),
    ('분청 귀얄 찻잔', 20, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p33_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p33_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/p33_C.webp');

UPDATE product p SET thumbnail_url = r.main_url
FROM demo_photoreal_c r WHERE r.title = p.title AND r.artisan_id = p.artisan_id AND r.main_url IS NOT NULL AND p.thumbnail_url LIKE '%/Jangingmall/backend/%/docs/%';

INSERT INTO product_detail_image (product_id, display_order, image_url)
SELECT p.product_id, 0, r.detail0_url FROM product p JOIN demo_photoreal_c r ON r.title = p.title AND r.artisan_id = p.artisan_id
WHERE r.detail0_url IS NOT NULL AND p.thumbnail_url LIKE '%/Jangingmall/backend/%/docs/%'
ON CONFLICT (product_id, display_order) DO UPDATE SET image_url = EXCLUDED.image_url;

INSERT INTO product_detail_image (product_id, display_order, image_url)
SELECT p.product_id, 1, r.detail1_url FROM product p JOIN demo_photoreal_c r ON r.title = p.title AND r.artisan_id = p.artisan_id
WHERE r.detail1_url IS NOT NULL AND p.thumbnail_url LIKE '%/Jangingmall/backend/%/docs/%'
ON CONFLICT (product_id, display_order) DO UPDATE SET image_url = EXCLUDED.image_url;

DELETE FROM product_detail_image d USING product p JOIN demo_photoreal_c r ON r.title = p.title AND r.artisan_id = p.artisan_id
WHERE d.product_id = p.product_id AND p.thumbnail_url LIKE '%/Jangingmall/backend/%/docs/%'
  AND ((r.main_url IS NOT NULL AND r.detail0_url IS NOT NULL AND r.detail1_url IS NOT NULL AND d.display_order >= 2)
    OR (r.main_url IS NOT NULL AND r.detail0_url IS NULL AND r.detail1_url IS NULL));

CREATE TEMP TABLE demo_photoreal_s (title VARCHAR(200), subcategory_id BIGINT, main_url VARCHAR(500),
    detail0_url VARCHAR(500), detail1_url VARCHAR(500)) ON COMMIT DROP;
INSERT INTO demo_photoreal_s VALUES
    ('신정희요 수제 이도다완', 1, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d002_A.webp', NULL, NULL),
    ('광주요 백자 청화 다기 3인 세트', 1, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d003_A.webp', NULL, NULL),
    ('강진 청자 운학문 다기 세트', 1, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d004_A.webp', NULL, NULL),
    ('이종덕 옻칠 목다완 찻잔', 1, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d005_A.webp', NULL, NULL),
    ('영남요 백자 3인 다기 찻잔', 1, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d006_A.webp', NULL, NULL),
    ('다도원 청자 상감 다관 및 잔세트', 1, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d007_A.webp', NULL, NULL),
    ('광주요 소리잔 찻잔 2인 세트', 1, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d008_A.webp', NULL, NULL),
    ('신정희요 분청 찻잔 5인세트', 1, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d009_A.webp', NULL, NULL),
    ('징광옹기 옹기 찻그릇 및 퇴수기', 1, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d010_A.webp', NULL, NULL),
    ('김정옥 백자 수제 다관', 1, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d011_A.webp', NULL, NULL),
    ('강진 청자 상감 모란문 찻잔', 1, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d012_A.webp', NULL, NULL),
    ('광주요 미수 백자 2인 다기세트', 1, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d013_A.webp', NULL, NULL),
    ('신정희요 덤벙이 다완', 1, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d014_A.webp', NULL, NULL),
    ('이종덕 나주 옻칠 찻잔 받침 세트', 1, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d015_A.webp', NULL, NULL),
    ('징광옹기 옹기 찻사발', 1, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d016_A.webp', NULL, NULL),
    ('영남요 청화백자 찻잔', 1, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d017_A.webp', NULL, NULL),
    ('전통 문양 현대식 다기 찻잔', 1, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d018_A.webp', NULL, NULL),
    ('이형근 방짜유기 원형 찬접시 5종 세트', 2, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d020_A.webp', NULL, NULL),
    ('광주요 먹빛 옥형 접시 세트', 2, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d021_A.webp', NULL, NULL),
    ('징광옹기 천연잿물 옹기 비빔밥 대접', 2, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d023_A.webp', NULL, NULL),
    ('허진규 옹기 숨쉬는 옹기 접시', 2, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d024_A.webp', NULL, NULL),
    ('김수영 방짜유기 무광 옥바리 밥그릇', 2, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d025_A.webp', NULL, NULL),
    ('이형근 방짜유기 면기 2인 세트', 2, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d026_A.webp', NULL, NULL),
    ('광주요 아뜰리에 먹빛 파스타볼', 2, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d034_A.webp', NULL, NULL),
    ('이형근 방짜유기 옥주병 술잔 세트', 4, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d056_A.webp', NULL, NULL),
    ('광주요 소리잔 미수 2인 세트', 4, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d057_A.webp', NULL, NULL),
    ('김정옥 영남요 백자 청화 주병', 4, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d058_A.webp', NULL, NULL),
    ('강진 청자 음각 연화문 주병 술잔 세트', 4, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d059_A.webp', NULL, NULL),
    ('징광옹기 옹기 머그컵 2인 세트', 4, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d060_A.webp', NULL, NULL),
    ('김수영 방짜유기 막걸리 잔 4개 세트', 4, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d061_A.webp', NULL, NULL),
    ('이형근 방짜유기 맥주잔 2인 세트', 4, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d062_A.webp', NULL, NULL),
    ('광주요 먹빛 링 머그컵 2종', 4, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d063_A.webp', NULL, NULL),
    ('남원목기 옻칠 원목 술잔 4인 세트', 4, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d064_A.webp', NULL, NULL),
    ('허진규 옹기 옹기 찻컵', 4, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d066_A.webp', NULL, NULL),
    ('강진 청자 상감 미니 술병', 4, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d068_A.webp', NULL, NULL),
    ('이종덕 무형유산 해주반 조각 소반', 5, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d072_A.webp', NULL, NULL),
    ('이종덕 통영반 옻칠 팔각 소반', 5, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d073_A.webp', NULL, NULL),
    ('남원목기 느티나무 옻칠 사각 트레이 쟁반', 5, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d074_A.webp', NULL, NULL),
    ('이종덕 전통 호족반 미니 소반', 5, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d075_A.webp', NULL, NULL),
    ('남원목기 물푸레나무 원형 쟁반', 5, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d076_A.webp', NULL, NULL),
    ('이종덕 구족반 전통 찻상', 5, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d077_A.webp', NULL, NULL),
    ('남원목기 옻칠 휴대용 접이식 찻상', 5, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d078_A.webp', NULL, NULL),
    ('이종덕 약소반 미니 옻칠 상', 5, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d079_A.webp', NULL, NULL),
    ('남원목기 느티나무 모서리 곡면 쟁반', 5, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d080_A.webp', NULL, NULL),
    ('이종덕 조선시대 해주형 꽃소반', 5, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d081_A.webp', NULL, NULL),
    ('남원목기 옻칠 손잡이 트레이', 5, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d082_A.webp', NULL, NULL),
    ('이종덕 사각 단각 소반', 5, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d083_A.webp', NULL, NULL),
    ('남원목기 원목 티트레이 쟁반', 5, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d084_A.webp', NULL, NULL),
    ('전통 문양 현대식 소반 쟁반', 5, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d085_A.webp', NULL, NULL),
    ('남원목기 산청 캄포 통나무 수제 도마', 6, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d087_A.webp', NULL, NULL),
    ('남원목기 박달나무 단단한 빵도마', 6, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d088_A.webp', NULL, NULL),
    ('김수영 방짜유기 단조 주방 부용 칼', 6, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d089_A.webp', NULL, NULL),
    ('남원목기 옻칠 원목 플레이팅 도마', 6, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d090_A.webp', NULL, NULL),
    ('비취 상감 은가락지', 17, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d219_A.webp', NULL, NULL),
    ('국화 매듭 드롭 귀걸이', 17, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d220_A.webp', NULL, NULL),
    ('호박 은조각 마노 반지', 17, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d221_A.webp', NULL, NULL),
    ('칠보 유기 원형 귀걸이', 17, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d222_A.webp', NULL, NULL),
    ('은 투각 모란문 반지', 17, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d223_A.webp', NULL, NULL),
    ('매듭 생동끈 미니 귀걸이', 17, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d224_A.webp', NULL, NULL),
    ('산호 은장식 마노 반지', 17, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d225_A.webp', NULL, NULL),
    ('백옥 링 은 귀걸이', 17, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d226_A.webp', NULL, NULL),
    ('전통 문양 현대식 반지 귀걸이', 17, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d227_A.webp', NULL, NULL),
    ('김은영 칠보 매듭 팔찌', 18, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d229_A.webp', NULL, NULL),
    ('은 상감 옥 펜던트 목걸이', 18, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d230_A.webp', NULL, NULL),
    ('김혜순 전통 도래 매듭 원석 팔찌', 18, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d231_A.webp', NULL, NULL),
    ('매듭 모란 자수 초커 목걸이', 18, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d232_A.webp', NULL, NULL),
    ('순은 체인 비취 펜던트 목걸이', 18, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d233_A.webp', NULL, NULL),
    ('김혜순 생동 매듭 실크 팔찌', 18, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d234_A.webp', NULL, NULL),
    ('자개 상감 매듭 롱 목걸이', 18, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d235_A.webp', NULL, NULL),
    ('은 세공 매화문 두 줄 팔찌', 18, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d236_A.webp', NULL, NULL),
    ('김혜순 무형유산 봉술 매듭 목걸이', 18, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d237_A.webp', NULL, NULL),
    ('오색 매듭 가죽 매치 팔찌', 18, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d238_A.webp', NULL, NULL),
    ('호박 원석 세공 은 목걸이', 18, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d239_A.webp', NULL, NULL),
    ('백옥 산호 2연 매듭 팔찌', 18, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d240_A.webp', NULL, NULL),
    ('전통 문양 현대식 목걸이 팔찌', 18, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d241_A.webp', NULL, NULL),
    ('김혜순 정통 명주실 매듭 단작 노리개', 19, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d243_A.webp', NULL, NULL),
    ('김은영 은장도 매듭 노리개', 19, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d244_A.webp', NULL, NULL),
    ('자개 모란 브로치', 19, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d245_A.webp', NULL, NULL),
    ('김혜순 백옥 나비 매듭 노리개', 19, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d246_A.webp', NULL, NULL),
    ('칠보 매화 코사지 브로치', 19, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d247_A.webp', NULL, NULL),
    ('김혜순 산호 가지 단작 노리개', 19, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d248_A.webp', NULL, NULL),
    ('은 투각 십장생 브로치', 19, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d249_A.webp', NULL, NULL),
    ('예당 전통 자수 화장품 파우치', 22, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d283_A.webp', NULL, NULL),
    ('구혜자 침선장 전통 색동 줌치 주머니', 22, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d284_A.webp', NULL, NULL),
    ('예당 자개 장식 매듭 클러치백', 22, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d285_A.webp', NULL, NULL),
    ('방연옥 한산모시 여름 마숄더백', 22, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d286_A.webp', NULL, NULL),
    ('예당 한복지 사각 미니 크로스백', 22, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d287_A.webp', NULL, NULL),
    ('구혜자 전통 궁중 약주머니', 22, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d288_A.webp', NULL, NULL),
    ('예당 전통 자수 안경 파우치 케이스', 22, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d289_A.webp', NULL, NULL),
    ('구혜자 전통 명주 조각보 에코백', 22, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d290_A.webp', NULL, NULL),
    ('예당 오색 매듭 복주머니 핸드백', 22, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d291_A.webp', NULL, NULL),
    ('방연옥 한산모시 천연염색 파우치 3종', 22, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d292_A.webp', NULL, NULL),
    ('예당 한복 양단 숄더백', 22, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d293_A.webp', NULL, NULL),
    ('구혜자 침선장 색동 미니 돈주머니', 22, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d294_A.webp', NULL, NULL),
    ('예당 손자수 매화 스트링 파우치', 22, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d295_A.webp', NULL, NULL),
    ('구혜자 전통 모시 조각보 클러치', 22, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d296_A.webp', NULL, NULL),
    ('예당 한복 원단 여행용 대형 파우치', 22, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d297_A.webp', NULL, NULL),
    ('전통 문양 현대식 가방 파우치', 22, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d298_A.webp', NULL, NULL),
    ('예당 한복지 조각보 슬림 카드지갑', 23, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d300_A.webp', NULL, NULL),
    ('구혜자 전통 누비 지퍼 동전지갑', 23, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d301_A.webp', NULL, NULL),
    ('예당 전통 자수 모란문 접이식 반지갑', 23, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d302_A.webp', NULL, NULL),
    ('예당 나전칠기 문양 가죽 명함 지갑', 23, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d303_A.webp', NULL, NULL),
    ('구혜자 전통 색동 쌈지 지갑', 23, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d304_A.webp', NULL, NULL),
    ('예당 매듭 술 장식 가죽 카드지갑', 23, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d305_A.webp', NULL, NULL),
    ('방연옥 한산모시 미니 카드지갑', 23, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d306_A.webp', NULL, NULL),
    ('예당 전통 십장생 자수 장지갑', 23, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d307_A.webp', NULL, NULL),
    ('구혜자 전통 실크 조각보 동전지갑', 23, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d308_A.webp', NULL, NULL),
    ('예당 모란문 음각 소가죽 카드홀더', 23, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d309_A.webp', NULL, NULL),
    ('구혜자 손자수 매화 삼각 지갑', 23, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d310_A.webp', NULL, NULL),
    ('예당 한복 양단 똑딱이 동전지갑', 23, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d311_A.webp', NULL, NULL),
    ('예당 전통 자수 아코디언 카드지갑', 23, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d312_A.webp', NULL, NULL),
    ('전통 문양 현대식 지갑 카드지갑', 23, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/d313_A.webp', NULL, NULL),
    ('김정옥 영남요 분청사기 다기세트', 1, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f01_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f01_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f01_C.webp'),
    ('김수영 방짜유기 4인 옥식기 옥접시 세트', 2, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f02_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f02_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f02_C.webp'),
    ('김수영 방짜유기 무광 수저 2벌 세트', 3, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f03_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f03_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f03_C.webp'),
    ('김수영 방짜유기 주전자 및 술잔 4인 세트', 4, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f04_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f04_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f04_C.webp'),
    ('이종덕 무형유산 나주반 전통 소반', 5, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f05_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f05_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f05_C.webp'),
    ('남원목기 느티나무 통원목 도마', 6, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f06_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f06_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f06_C.webp'),
    ('징광옹기 전통 천연잿물 씨간장 항아리 20L', 7, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f07_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f07_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f07_C.webp'),
    ('허진규 옹기 전통 옹기 무균 뚝배기', 8, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f08_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f08_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f08_C.webp'),
    ('남원목기 무형유산 옻칠 목제기 47P 풀세트', 9, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f09_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f09_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f09_C.webp'),
    ('에이치케이스튜디오 활짝핀 연꽃 LED 조명 오르골', 10, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f10_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f10_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f10_C.webp'),
    ('이형만 무형유산 나전칠기 적매화 한지 보석함', 11, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f11_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f11_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f11_C.webp'),
    ('조화자 백자 청화 도자기 화병', 12, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f12_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f12_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f12_C.webp'),
    ('이형만 나전칠기 십장생문 탁상시계', 13, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f13_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f13_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f13_C.webp'),
    ('소품쟁이 삼베 고급 전통 문양 발', 14, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f14_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f14_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f14_C.webp'),
    ('양석중 무형유산 사방탁자 4단 원목 가구', 15, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f15_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f15_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f15_C.webp'),
    ('김극천 무형유산 황동 나비 장석 2개 세트', 16, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f16_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f16_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f16_C.webp'),
    ('전통 은가락지 세트 (2개입)', 17, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f17_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f17_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f17_C.webp'),
    ('김혜순 무형유산 병아리 매듭 목걸이', 18, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f18_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f18_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f18_C.webp'),
    ('김혜순 무형유산 삼작 노리개', 19, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f19_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f19_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f19_C.webp'),
    ('전통 순은 용두 비녀', 20, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f20_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f20_B.webp', NULL),
    ('방연옥 무형유산 한산모시 100% 옥색 스카프', 21, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f21_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f21_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f21_C.webp'),
    ('예당 한복 원단 전통 조각보 토트백', 22, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f22_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f22_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f22_C.webp'),
    ('예당 전통 나전 자개 포인트 장장어 지갑', 23, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f23_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f23_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f23_C.webp'),
    ('김기찬 무형유산 하회탈 양반 부네 열쇠고리 세트', 24, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f24_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f24_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f24_C.webp'),
    ('김기찬 무형유산 설송 합죽선 매화 부채', 25, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f25_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f25_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f25_C.webp'),
    ('구혜자 무형유산 당의 한복 맞춤 세트', 26, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f26_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f26_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f26_C.webp'),
    ('정춘모 무형유산 흑대립 정통 조선 갓', 27, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f27_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f27_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f27_C.webp'),
    ('정춘모 무형유산 말총 망건', 28, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f28_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f28_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f28_C.webp'),
    ('성심필방 전통 수제 겸호필 붓 세트 (3종)', 29, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f29_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f29_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f29_C.webp'),
    ('윤규상 무형유산 수제 닥종이 한지 편지지 세트', 30, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f30_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f30_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f30_C.webp'),
    ('숍오브코리아 나전칠기 나비 자개 수제 볼펜', 31, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f31_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f31_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f31_C.webp'),
    ('숍오브코리아 나전칠기 적매화 자개 명함집', 32, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f32_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f32_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f32_C.webp'),
    ('숍오브코리아 나전칠기 적매화 한지 필함 필통', 33, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f33_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f33_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f33_C.webp'),
    ('구혜자 무형유산 정통 양단 방석 (2개 세트)', 34, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f34_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f34_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f34_C.webp'),
    ('구혜자 무형유산 정통 명주 실크 솜이불', 35, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f35_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f35_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f35_C.webp'),
    ('방연옥 한산모시 천연염색 식탁 러너 (길이 150cm)', 36, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f36_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f36_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f36_C.webp'),
    ('장윤영 미니 보자기 - 흉배보', 37, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f37_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f37_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f37_C.webp'),
    ('박인숙 강릉자수 보자기 안경닦이 겸 손수건', 38, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f38_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f38_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f38_C.webp'),
    ('방연옥 한산모시 천연염색 주방 앞치마', 39, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f39_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f39_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f39_C.webp'),
    ('윤규상 무형유산 한지 조각우산 (대) - 7색', 40, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f40_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f40_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f40_C.webp'),
    ('박인숙 강릉자수 모란문 수자수 액자', 41, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f41_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f41_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f41_C.webp'),
    ('종로불교사 일월오봉도 캔버스 아트 액자', 42, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f42_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f42_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f42_C.webp'),
    ('종로불교사 일월오봉도 금병풍 (4폭)', 43, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f43_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f43_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f43_C.webp'),
    ('김각한 무형유산 화성행궁 현판 서각 복원작', 44, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f44_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f44_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f44_C.webp'),
    ('담양한과 3단 예향 명절 한과선물세트', 55, NULL, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f55_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f55_C.webp'),
    ('담양한과 궁중 명가 한과 육포 종합 선물세트', 56, 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f56_A.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f56_B.webp', 'https://raw.githubusercontent.com/Jangingmall/backend/develop/docs/demo-products/photoreal/staging/f56_C.webp');

UPDATE product p SET thumbnail_url = r.main_url
FROM demo_photoreal_s r WHERE r.title = p.title AND r.subcategory_id = p.subcategory_id AND r.main_url IS NOT NULL AND p.thumbnail_url LIKE '%/Jangingmall/backend/%/docs/%';

INSERT INTO product_detail_image (product_id, display_order, image_url)
SELECT p.product_id, 0, r.detail0_url FROM product p JOIN demo_photoreal_s r ON r.title = p.title AND r.subcategory_id = p.subcategory_id
WHERE r.detail0_url IS NOT NULL AND p.thumbnail_url LIKE '%/Jangingmall/backend/%/docs/%'
ON CONFLICT (product_id, display_order) DO UPDATE SET image_url = EXCLUDED.image_url;

INSERT INTO product_detail_image (product_id, display_order, image_url)
SELECT p.product_id, 1, r.detail1_url FROM product p JOIN demo_photoreal_s r ON r.title = p.title AND r.subcategory_id = p.subcategory_id
WHERE r.detail1_url IS NOT NULL AND p.thumbnail_url LIKE '%/Jangingmall/backend/%/docs/%'
ON CONFLICT (product_id, display_order) DO UPDATE SET image_url = EXCLUDED.image_url;

DELETE FROM product_detail_image d USING product p JOIN demo_photoreal_s r ON r.title = p.title AND r.subcategory_id = p.subcategory_id
WHERE d.product_id = p.product_id AND p.thumbnail_url LIKE '%/Jangingmall/backend/%/docs/%'
  AND ((r.main_url IS NOT NULL AND r.detail0_url IS NOT NULL AND r.detail1_url IS NOT NULL AND d.display_order >= 2)
    OR (r.main_url IS NOT NULL AND r.detail0_url IS NULL AND r.detail1_url IS NULL));
