"""시연용 큐레이션 상품 33개 — 이름·소개·특징·이미지가 서로 맞도록 한곳에서 관리하는 원본.

여기서 docs/demo-products/*.webp (일러스트), docs/demo-products/README.md (표),
src/main/resources/db/migration/V17__demo_curated_products.sql 이 만들어진다.
  python3 scripts/demo-products/generate.py
"""

# 색 이름 → (배경 위, 배경 아래, 포인트, 진한 색, 밝은 색)
PALETTES = {
    "rose":   ("#fbeef1", "#efd3da", "#d9738f", "#7a2a43", "#f6c9d6"),
    "indigo": ("#eef1f8", "#d3dbe9", "#3b5a99", "#1d2f5a", "#c6d3ee"),
    "plum":   ("#f7eef5", "#e6d2e1", "#9b4f86", "#4f1f48", "#e8c4de"),
    "green":  ("#eff5ec", "#d5e3cf", "#5f8f4e", "#2c4a22", "#cfe6c3"),
    "teal":   ("#ecf5f4", "#cfe4e1", "#2f8f8a", "#134a47", "#bfe3df"),
    "silver": ("#f1f3f5", "#d5dbe0", "#8d99a6", "#3a4552", "#dfe5ea"),
    "ochre":  ("#f8f1e2", "#e6d4ad", "#c0912f", "#5a3f0e", "#f0dca8"),
    "amber":  ("#fbf3df", "#ecd9aa", "#d9902b", "#6b3f0a", "#f6d98b"),
    "sky":    ("#eef4fa", "#d3e3f2", "#5b9bd5", "#25496e", "#cfe3f7"),
    "natural": ("#f4f0e6", "#ded4bd", "#a38b5c", "#4a3b1f", "#e6dbbd"),
    "white":  ("#f6f7f8", "#dfe3e6", "#9aa5ad", "#41505a", "#eef2f4"),
    "mint":   ("#eefaf3", "#cfeadb", "#3aa876", "#17543a", "#c3efd8"),
    "jade":   ("#eef7f2", "#cfe6da", "#3f9a78", "#154a36", "#bfe8d3"),
    "gold":   ("#faf3df", "#ecdca8", "#c9a227", "#5d4708", "#f3e3a0"),
    "navy":   ("#eceff6", "#cdd5e6", "#2b3f7a", "#12204a", "#c3cde8"),
    "pearl":  ("#f9f6f1", "#e8e0d4", "#b8a898", "#4e4036", "#f3ece3"),
    "mop":    ("#eef5f3", "#cfe1dc", "#4f8f9c", "#1f4650", "#cfe9ee"),
    "ivory":  ("#faf6ea", "#e9e0c6", "#b9a46a", "#4d4220", "#f3ecd3"),
    "ink":    ("#f1f1f1", "#d6d6d6", "#4a4a4a", "#141414", "#d9d9d9"),
}

# detail_images: 상세 갤러리에서 자동으로 그린 특징 카드·상품 정보 카드 뒤에 덧붙일 이미지(이미 만든 시연 일러스트).
# image: None 이면 위 팔레트로 새로 그린다. 문자열이면 이미 만든 시연 일러스트(docs/ 기준 경로)를 쓴다.
# 장인(artisan)·소분류(sub) 번호는 시드 데이터(V7·V9) 기준이다.
PRODUCTS = [
    # ── 구혜자 침선공방(31): 한복·주머니·스카프 ────────────────────────────
    dict(key="p01", name="연분홍 모시 생활한복 저고리", artisan=31, sub=26, kind="hanbok", color="rose", price=128000, stock=8,
         material="한산모시", days=14, themes=["PARENTS", "BIRTHDAY_60TH"], tags=["전통공예", "선물", "여름"], colors=["연분홍"],
         intro="바람이 잘 통하는 한산모시로 지은 연분홍 저고리입니다. 평상복으로 입기 편하게 품을 넉넉히 잡았습니다.",
         features=["한산모시 100%", "손바느질 마감", "품 넉넉한 생활한복 패턴"]),
    dict(key="p02", name="쪽빛 누비 복주머니", artisan=31, sub=37, kind="pouch", color="indigo", price=38000, stock=20,
         material="면 누비", days=10, themes=["FRIEND", "WEDDING"], tags=["전통공예", "선물", "복"], colors=["쪽빛"],
         intro="쪽빛 천을 누벼 만든 작은 복주머니입니다. 새해나 결혼 선물로 마음을 담아 건네기 좋습니다.",
         features=["손누비 마감", "매듭 끈 장식", "손바닥 크기"]),
    dict(key="p03", name="매화 자수 손수건 세트", artisan=31, sub=38, kind="handkerchief", color="plum", price=24000, stock=30,
         material="무명", days=7, themes=["FRIEND", "PROMOTION"], tags=["자수", "선물", "일상"], colors=["자주"],
         intro="매화 한 가지를 손으로 수놓은 무명 손수건 두 장 세트입니다. 부드러워 매일 쓰기 좋습니다.",
         features=["손자수 매화", "부드러운 무명", "2장 1세트"]),
    dict(key="p04", name="오방색 조각보 파우치", artisan=31, sub=22, kind="bag", color="ochre", price=52000, stock=15,
         material="명주", days=12, themes=["FRIEND"], tags=["조각보", "전통공예", "일상"], colors=["오방색"],
         intro="남은 천을 이어 붙이는 조각보 기법으로 만든 파우치입니다. 같은 무늬가 하나도 없습니다.",
         features=["조각보 기법", "안감 포함", "지퍼 마감"]),
    dict(key="p05", name="연둣빛 모시 스카프", artisan=31, sub=21, kind="scarf", color="green", price=46000, stock=18,
         material="모시", days=10, themes=["PARENTS"], tags=["여름", "선물", "전통공예"], colors=["연두"],
         intro="가볍고 시원한 모시로 짠 연둣빛 스카프입니다. 한여름 목에 둘러도 답답하지 않습니다.",
         features=["통풍이 좋은 모시", "가벼운 무게", "끝단 술 장식"]),
    # ── 예당한복 소품(36): 노리개·키링·지갑·비녀 ───────────────────────────
    dict(key="p06", name="홍매 삼작 노리개", artisan=36, sub=19, kind="norigae", color="rose", price=98000, stock=6,
         material="명주실", days=21, themes=["WEDDING"], tags=["혼례", "전통공예", "선물"], colors=["홍색"],
         intro="붉은 매듭에 세 가지 장식을 단 삼작 노리개입니다. 한복에 달면 단아한 포인트가 됩니다.",
         features=["삼작 구성", "손매듭 끈", "한복 고름에 걸어 사용"]),
    dict(key="p07", name="쪽빛 매듭 키링", artisan=36, sub=24, kind="keyring", color="indigo", price=18000, stock=40,
         material="명주실", days=5, themes=["FRIEND", "PROMOTION"], tags=["매듭", "일상", "선물"], colors=["쪽빛"],
         intro="전통 매듭을 작게 엮은 키링입니다. 가방이나 열쇠에 달면 한국의 멋이 은은하게 묻어납니다.",
         features=["손매듭", "가벼운 무게", "작은 선물로 적합"]),
    dict(key="p08", name="조각보 카드지갑", artisan=36, sub=23, kind="wallet", color="teal", price=42000, stock=22,
         material="명주", days=10, themes=["PROMOTION", "FRIEND"], tags=["조각보", "일상", "선물"], colors=["청록"],
         intro="조각보 천으로 만든 슬림한 카드지갑입니다. 카드 여섯 장과 지폐를 넣을 수 있습니다.",
         features=["카드 6칸", "조각보 무늬", "얇은 두께"]),
    dict(key="p09", name="은빛 매화 비녀", artisan=36, sub=20, kind="hairpin", color="silver", price=76000, stock=9,
         material="은", days=18, themes=["WEDDING", "BIRTHDAY_60TH"], tags=["혼례", "전통공예", "장신구"], colors=["은색"],
         intro="끝에 매화 한 송이를 새긴 은 비녀입니다. 쪽머리뿐 아니라 올림머리에도 단정하게 어울립니다.",
         features=["순은 도금", "매화 문양 조각", "길이 약 14cm"]),
    dict(key="p10", name="옥빛 매듭 귀걸이", artisan=36, sub=17, kind="ring", color="jade", price=54000, stock=14,
         material="옥·명주실", days=14, themes=["FRIEND", "WEDDING"], tags=["장신구", "선물", "전통공예"], colors=["옥색"],
         intro="옥빛 구슬에 작은 매듭을 단 귀걸이입니다. 가볍게 흔들리는 모양이 얼굴을 환하게 밝혀 줍니다.",
         features=["옥빛 구슬", "손매듭 장식", "알레르기 줄인 은침"]),
    # ── 소품쟁이 자수표구(25): 자수 액자·조명·방석·러너 ────────────────────
    dict(key="p11", name="수자수 모란도 액자", artisan=25, sub=41, kind="embroidery", color="rose", price=185000, stock=4,
         material="명주 수자수", days=45, themes=["HOUSEWARMING", "WEDDING"], tags=["자수", "집들이", "인테리어"], colors=["분홍"],
         intro="모란을 한 올 한 올 수놓아 표구한 자수 액자입니다. 부귀를 뜻하는 꽃이라 집들이 선물로 많이 찾습니다.",
         features=["손수자수", "원목 액자 표구", "가로 40cm × 세로 50cm"]),
    dict(key="p12", name="한지 산수화 액자", artisan=25, sub=42, kind="frame", color="green", price=98000, stock=7,
         material="한지", days=20, themes=["HOUSEWARMING"], tags=["인테리어", "한지", "전통공예"], colors=["녹색"],
         intro="한지 위에 먹과 채색으로 산수를 그린 액자입니다. 거실이나 서재 벽에 차분한 분위기를 더합니다.",
         features=["수제 한지", "먹·채색 산수화", "원목 액자"]),
    dict(key="p13", name="오방 누비 방석", artisan=25, sub=34, kind="cushion", color="ochre", price=64000, stock=12,
         material="명주 누비", days=14, themes=["HOUSEWARMING", "PARENTS"], tags=["누비", "인테리어", "일상"], colors=["황토"],
         intro="오방색을 이어 누빈 방석입니다. 바닥에 앉아 지내는 시간이 푹신하고 따뜻해집니다.",
         features=["손누비", "솜 충전 두께 5cm", "가로·세로 45cm"]),
    dict(key="p14", name="모시 테이블 러너", artisan=25, sub=36, kind="tablecloth", color="ivory", price=72000, stock=10,
         material="모시", days=12, themes=["HOUSEWARMING"], tags=["인테리어", "집들이", "여름"], colors=["아이보리"],
         intro="상차림 가운데 길게 깔아 쓰는 모시 러너입니다. 은은한 결이 식탁을 단정하게 만들어 줍니다.",
         features=["모시 100%", "가장자리 술 장식", "길이 150cm"]),
    dict(key="p15", name="한지 무드 조명", artisan=25, sub=10, kind="lamp", color="amber", price=89000, stock=8,
         material="한지·원목", days=16, themes=["HOUSEWARMING", "PROMOTION"], tags=["조명", "인테리어", "한지"], colors=["호박색"],
         intro="한지를 두른 스탠드 조명입니다. 불을 켜면 한지 결 사이로 따뜻한 빛이 퍼져 방이 포근해집니다.",
         features=["한지 갓", "원목 받침", "전구 색온도 2700K"]),
    # ── 방연옥 한산모시(32): 모시 제품 ───────────────────────────────────
    dict(key="p16", name="하늘빛 한산모시 스카프", artisan=32, sub=21, kind="scarf", color="sky", price=58000, stock=16,
         material="한산모시", days=12, themes=["PARENTS", "BIRTHDAY_60TH"], tags=["여름", "선물", "전통공예"], colors=["하늘색"],
         intro="한산모시를 하늘빛으로 물들인 스카프입니다. 바람이 지나가듯 가벼워 여름 외출에 잘 어울립니다.",
         features=["천연 염색", "한산모시 100%", "가로 40cm × 세로 160cm"]),
    dict(key="p17", name="모시 주방 앞치마", artisan=32, sub=39, kind="apron", color="natural", price=68000, stock=12,
         material="한산모시", days=10, themes=["HOUSEWARMING"], tags=["주방", "집들이", "일상"], colors=["자연색"],
         intro="통풍이 잘 되고 물이 빨리 마르는 모시 앞치마입니다. 주방일이 한결 가벼워집니다.",
         features=["물 빠짐이 빠른 모시", "주머니 포함", "끈 길이 조절"]),
    dict(key="p18", name="모시 홑이불", artisan=32, sub=35, kind="bedding", color="white", price=148000, stock=5,
         material="한산모시", days=25, themes=["PARENTS", "BIRTHDAY_60TH", "WEDDING"], tags=["여름", "혼수", "선물"], colors=["흰색"],
         intro="여름밤 덮고 자면 시원한 모시 홑이불입니다. 부모님께 드리는 선물이나 혼수로 많이 찾습니다.",
         features=["한산모시", "시원한 촉감", "퀸 사이즈"]),
    dict(key="p19", name="민트 모시 보자기", artisan=32, sub=37, kind="pouch", color="mint", price=32000, stock=24,
         material="모시", days=7, themes=["WEDDING", "FRIEND"], tags=["포장", "선물", "전통공예"], colors=["민트"],
         intro="선물을 감싸는 모시 보자기입니다. 포장 후에도 스카프나 벽장식으로 다시 쓸 수 있습니다.",
         features=["가로·세로 50cm", "가장자리 박음질", "재사용 가능"]),
    dict(key="p20", name="모시 개량한복 상의", artisan=32, sub=26, kind="hanbok", color="mint", price=138000, stock=7,
         material="한산모시", days=18, themes=["PARENTS"], tags=["여름", "생활한복", "선물"], colors=["연두"],
         intro="일상에서도 입을 수 있게 단순하게 다듬은 모시 상의입니다. 시원하고 구김이 자연스럽습니다.",
         features=["한산모시", "단순한 선", "남녀 공용 프리 사이즈"]),
    # ── 이금희 장신구(34): 매듭·은·옥 장신구 ──────────────────────────────
    dict(key="p21", name="은 매듭 팔찌", artisan=34, sub=18, kind="necklace", color="silver", price=64000, stock=11,
         material="은", days=14, themes=["FRIEND", "PARENTS"], tags=["장신구", "선물", "매듭"], colors=["은색"],
         intro="은실을 전통 매듭으로 엮은 팔찌입니다. 손목에 가볍게 감겨 매일 하기 편합니다.",
         features=["순은", "손매듭", "길이 조절 가능"]),
    dict(key="p22", name="옥 노리개 브로치", artisan=34, sub=19, kind="norigae", color="jade", price=88000, stock=6,
         material="옥·명주실", days=21, themes=["PARENTS", "BIRTHDAY_60TH"], tags=["장신구", "전통공예", "선물"], colors=["옥색"],
         intro="옥 장식에 매듭을 단 노리개 브로치입니다. 한복에도, 평소 재킷에도 달 수 있습니다.",
         features=["천연 옥", "손매듭", "브로치 핀 겸용"]),
    dict(key="p23", name="칠보 푸른 반지", artisan=34, sub=17, kind="ring", color="indigo", price=72000, stock=9,
         material="은·칠보", days=18, themes=["FRIEND", "WEDDING"], tags=["장신구", "칠보", "선물"], colors=["푸른색"],
         intro="푸른 칠보 유약을 올린 은 반지입니다. 빛에 따라 깊이가 달라 보입니다.",
         features=["칠보 유약", "순은 몸체", "사이즈 제작 가능"]),
    dict(key="p24", name="금빛 떨잠", artisan=34, sub=20, kind="hairpin", color="gold", price=120000, stock=4,
         material="도금 은", days=28, themes=["WEDDING"], tags=["혼례", "전통공예", "장신구"], colors=["금색"],
         intro="혼례 때 머리 앞을 장식하는 떨잠입니다. 흔들릴 때마다 은은하게 반짝입니다.",
         features=["도금 은", "손조각", "혼례·돌잔치용"]),
    dict(key="p25", name="진주 매듭 목걸이", artisan=34, sub=18, kind="necklace", color="pearl", price=98000, stock=8,
         material="담수 진주·명주실", days=16, themes=["WEDDING", "BIRTHDAY_60TH"], tags=["장신구", "선물", "혼례"], colors=["진주색"],
         intro="진주 사이를 손매듭으로 이은 목걸이입니다. 한복과 양장에 모두 잘 어울립니다.",
         features=["담수 진주", "손매듭", "길이 45cm"]),
    # ── 한국전통공예품몰(40): 나전·한지·문방 ───────────────────────────────
    dict(key="p26", name="나전 명함집", artisan=40, sub=32, kind="cardcase", color="mop", price=56000, stock=18,
         material="나전·옻칠", days=20, themes=["BOSS", "PROMOTION", "CORPORATE"], tags=["나전", "업무", "선물"], colors=["청록"],
         intro="자개를 박아 옻칠한 명함집입니다. 명함을 건넬 때 첫인상이 한층 단정해집니다.",
         features=["나전 장식", "옻칠 마감", "명함 30장 수납"]),
    dict(key="p27", name="나전 필통", artisan=40, sub=33, kind="pencup", color="teal", price=48000, stock=20,
         material="나전·원목", days=16, themes=["BOSS", "PROMOTION"], tags=["나전", "문방", "선물"], colors=["청록"],
         intro="책상 위에 두면 은은하게 빛나는 나전 필통입니다. 필기구 열 자루가 넉넉히 들어갑니다.",
         features=["자개 장식", "원목 몸체", "필기구 10자루"]),
    dict(key="p28", name="칠보 문양 만년필", artisan=40, sub=31, kind="pen", color="navy", price=88000, stock=10,
         material="황동·칠보", days=14, themes=["BOSS", "PROMOTION"], tags=["문방", "업무", "선물"], colors=["남색"],
         intro="몸통에 칠보 문양을 올린 만년필입니다. 부드럽게 써지고 손에 닿는 무게가 안정적입니다.",
         features=["칠보 몸통", "중자 촉", "잉크 컨버터 포함"]),
    dict(key="p29", name="서예 붓·먹·벼루 세트", artisan=40, sub=29, kind="brush", color="ink", price=120000, stock=6,
         material="양모·송연먹·청석", days=12, themes=["BOSS", "PARENTS"], tags=["서예", "문방", "선물"], colors=["먹색"],
         intro="붓, 먹, 벼루를 한 상자에 담은 서예 입문 세트입니다. 처음 먹을 가는 순간부터 정갈해집니다.",
         features=["양모 붓 2자루", "송연먹", "청석 벼루"]),
    dict(key="p30", name="한지 편지지 세트", artisan=40, sub=30, kind="paper", color="ivory", price=22000, stock=35,
         material="수제 한지", days=7, themes=["FRIEND", "PARENTS"], tags=["한지", "문방", "선물"], colors=["아이보리"],
         intro="결이 살아 있는 수제 한지 편지지와 봉투 세트입니다. 손글씨로 마음을 전하기 좋습니다.",
         features=["수제 한지", "편지지 20장·봉투 10장", "먹이 번지지 않음"]),
    # ── 시연 흐름 ① 전주 합죽선, ② 청자·분청 찻잔: 이미 그려 둔 일러스트를 그대로 쓴다 ─────────
    dict(key="p31", name="전주 합죽선 · 매화선", artisan=41, sub=25, kind="fan", color="rose", price=150000, stock=10,
         material="대나무·한지", days=14, themes=["BIRTHDAY_60TH", "WEDDING"], tags=["전통공예", "선물", "부채"], colors=["흰색"],
         intro="담양 왕대를 3년 건조해 손으로 겉대·속대를 깎고, 한지를 겹겹이 붙여 선면을 만들었습니다. 매화를 한 획씩 직접 그려 같은 부채가 하나도 없습니다.",
         features=["대나무 겉대 두 쪽을 붙인 합죽선", "닥나무 한지 선면", "선추 달린 접부채"],
         image="demo-images/hapjukseon-maehwa-illustrated/01-hero.webp",
         detail_images=["demo-images/hapjukseon-maehwa-illustrated/03-detail.webp",
                        "demo-images/hapjukseon-maehwa-illustrated/06-detail-02.webp"]),
    dict(key="p32", name="청자 운학문 찻잔", artisan=20, sub=1, kind="teacup", color="teal", price=85000, stock=12,
         material="청자", days=21, themes=["BIRTHDAY_60TH", "PARENTS", "BOSS"], tags=["다도", "전통공예", "선물"], colors=["비색"],
         intro="푸른 비색 유약에 학과 구름을 상감한 찻잔입니다. 차를 따르면 유약의 푸른빛이 은은하게 비칩니다.",
         features=["비색 유약", "운학문 상감", "용량 약 150ml"],
         image="demo-images/cheongja-bunjeong-teacup/01-hero-celadon.webp",
         detail_images=["demo-images/cheongja-bunjeong-teacup/05-detail-foot.webp",
                        "demo-images/cheongja-bunjeong-teacup/06-gift-set.webp"]),
    dict(key="p33", name="분청 귀얄 찻잔", artisan=20, sub=1, kind="teacup", color="natural", price=72000, stock=14,
         material="분청사기", days=21, themes=["HOUSEWARMING", "FRIEND"], tags=["다도", "전통공예", "선물"], colors=["회백색"],
         intro="백토를 귀얄(풀비)로 쓸듯이 바르고 철화로 풀꽃을 그린 분청 찻잔입니다. 투박한 붓결이 손에 따뜻하게 잡힙니다.",
         features=["백토 귀얄 분장", "철화 풀꽃 무늬", "용량 약 150ml"],
         image="demo-images/cheongja-bunjeong-teacup/02-hero-bunjeong.webp",
         detail_images=["demo-images/cheongja-bunjeong-teacup/03-pair.webp",
                        "demo-images/cheongja-bunjeong-teacup/04-techniques.webp"]),
]
